name: Create Android Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v3

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Setup dependencies
      run: |
        sudo apt install ninja-build -y
        AV1_MODULE_PATH="$(pwd)/libraries/decoder_av1/src/main"
        git clone https://github.com/google/cpu_features.git ${AV1_MODULE_PATH}/jni/cpu_features
        git clone https://chromium.googlesource.com/codecs/libgav1 ${AV1_MODULE_PATH}/jni/libgav1
        git clone https://github.com/abseil/abseil-cpp.git ${AV1_MODULE_PATH}/jni/libgav1/third_party/abseil-cpp
        git clone https://github.com/androidx/media.git

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleFossDebug

    - name: Set environment variables
      run: |
        echo "APK_SHA256=$(sha256sum app/build/outputs/apk/foss/debug/*.apk | awk '{ print $1 }')" >> $GITHUB_ENV

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          > ${{ github.event.head_commit.message }}
          
          * **APK SHA-256 Checksum**: `${{ env.APK_SHA256 }}`
        files: |
          app/build/outputs/apk/foss/debug/*.apk
        tag_name: "${{ github.run_number }}-${{ github.run_id }}"
